### ISSUE TITLE
Connecting node hyperdrive with browser based WebRTC hyperdrive

### ISSUE THREAD

**Issue by Juice10** [mafintosh/hyperdrive#17]
Would it be possible to have the node version talk to the browser version of the script?

Currently if I try to connect the second example in the `README.md` (example code below) to the browser based version (eg. http://mafintosh.github.io/hyperdrive/) the script crashes with the following error:
```javascript
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED [browsers ip address]:[random port number]
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

## Example code
```javascript
var disc = require('discovery-channel')()
var hyperdrive = require('hyperdrive')
var net = require('net');
var levelup = require('levelup')
var aLevelDB = levelup('./mydb')
var drive = hyperdrive(aLevelDB)

var link = new Buffer({your-hyperdrive-link-from-the-above-example}, 'hex')

var server = net.createServer(function (socket) {
  socket.pipe(drive.createPeerStream()).pipe(socket)
})

server.listen(0, function () {
  function ann () {
    // discovery-channel currently only works with 20 bytes hashes
    disc.announce(link.slice(0, 20), server.address().port)
  }

  ann()
  setInterval(ann, 10000)

  var lookup = disc.lookup(link.slice(0, 20))

  lookup.on('peer', function (ip, port) {
    var socket = net.connect(port, ip)
    socket.pipe(drive.createPeerStream()).pipe(socket)
  })
})
```

**Comment by piedshag** [comment]
use this code in the browser
```js
var swarm = require('webrtc-swarm')
var signalhub = require('signalhub')
var hyperdrive = require('hyperdrive')
var level = require('level-browserify')

var db = level('./mydb')
var drive = hyperdrive(db)

var link = new Buffer({your-hyperdrive-link-from-example-below}, 'hex')

// swarm logic

var hub = signalhub('swarm-example', ['https://instant.io:8080'])

var sw = swarm(hub)

sw.on('peer', function (peer, id) {
  peer.pipe(drive.createPeerStream()).pipe(peer)
})
```
and then use this on your computer
```js
var hyperdrive = require('hyperdrive')
var fs = require('fs')
var levelup = require('levelup')
var swarm = require('webrtc-swarm')
var signalhub = require('signalhub')
var wrtc = require('wrtc')

var aLevelDB = levelup('./my-drive')
var drive = hyperdrive(aLevelDB)

var pack = drive.add()

var stream = pack.entry({
  name: 'my-file.txt',
  mode: 0644
})

fs.createReadStream('my-file.txt').pipe(stream)

pack.finalize(function () {
  var link = pack.id.toString('hex')
  console.log(link, '<-- this is your hyperdrive link')
})

// swarm logic

var hub = signalhub('swarm-example', ['https://instant.io:8080'])

var sw = swarm(hub, {
  wrtc: wrtc // allows you to use webrtc in a desktop environment
})

sw.on('peer', function (peer, id) {
  peer.pipe(drive.createPeerStream()).pipe(peer)
})
```

**Comment by karissa** [comment]
This would be cool in a module! Could it go in discovery channel @mafintosh ?

**Comment by mafintosh** [comment]
discovery-channel doesn't create connections - only does peer discovery based on IPs/ports. using a specific swarm for webrtc seems like the best approach for now to me since the webrtc handshake requires more back-and-forth than a normal tcp/utp handshake.

**Comment by mafintosh** [comment]
@Juice10 hyperdrive is transport agnostic - it can work over any node stream. using webrtc-swarm like @piedshag describes you can get node to interopt with webrtc using the wrtc module. beware that the the wrtc module is a massive native dependency that can be tricky to get to work.

**Comment by mafintosh** [comment]
@karissa a mega swarm module that tries to connect all the things could be a good idea for a module though (or maybe the worst idea hehe)
