### ISSUE TITLE
Error: Invalid enum value: 39725

### ISSUE THREAD

**Issue by substack** [mafintosh/hyperdrive#48]
After the second file I store in an archive, I get this error:

```
Error: Invalid enum value: 39725
    at Object.decode (eval at <anonymous> (/home/substack/projects/hyperdrive/node_modules/generate-function/index.js:55:21), <anonymous>:5:50)
    at Object.decode (eval at <anonymous> (/home/substack/projects/hyperdrive/node_modules/generate-function/index.js:55:21), <anonymous>:31:27)
    at /home/substack/projects/hyperdrive/index.js:391:36
    at /home/substack/projects/hyperdrive/node_modules/levelup/lib/levelup.js:230:7
```

Here's the hex dump of the value that `messages.Index.decode(buf)` fails on:

```
080012213132373638383131303937373532363039362f4453435f3130323933322e6a706718adb6022005
```

**Comment by substack** [comment]
I've seen this error in a second project, consistently with the number 14. Investigating.

**Comment by substack** [comment]
More information: this seems like an issue in the non-live archive mode.

**Comment by mafintosh** [comment]
should be fixed in latest which is also LTS in terms of wire protocols / storage.
