### ISSUE TITLE
possible mem leak, investigate

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/hyperdrive#68]
```
> dat.haus@0.0.0 start /home/maf/versions/dat.haus-1466086479375
> taco-nginx --domain dat.haus node index.js

Server is listening on port 41616
(node) warning: possible EventEmitter memory leak detected. 11 download listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Feed.addListener (events.js:239:17)
    at onindex (/home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/archive.js:432:18)
    at /home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/archive.js:421:7
    at /home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/node_modules/hypercore/node_modules/subleveldown/node_modules/levelup/lib/levelup.js:230:7
(node) warning: possible EventEmitter memory leak detected. 11 upload listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Feed.addListener (events.js:239:17)
    at onindex (/home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/archive.js:436:18)
    at /home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/archive.js:421:7
    at /home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/node_modules/hypercore/node_modules/subleveldown/node_modules/levelup/lib/levelup.js:230:7
(node) warning: possible EventEmitter memory leak detected. 11 download listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Feed.addListener (events.js:239:17)
    at onindex (/home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/archive.js:432:18)
    at /home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/archive.js:421:7
    at /home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/node_modules/hypercore/node_modules/subleveldown/node_modules/levelup/lib/levelup.js:230:7
(node) warning: possible EventEmitter memory leak detected. 11 upload listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Feed.addListener (events.js:239:17)
    at onindex (/home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/archive.js:436:18)
    at /home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/archive.js:421:7
    at /home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/node_modules/hypercore/node_modules/subleveldown/node_modules/levelup/lib/levelup.js:230:7
(node) warning: possible EventEmitter memory leak detected. 11 download listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Feed.addListener (events.js:239:17)
    at onindex (/home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/archive.js:432:18)
    at /home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/archive.js:421:7
    at /home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/node_modules/hypercore/node_modules/subleveldown/node_modules/levelup/lib/levelup.js:230:7
(node) warning: possible EventEmitter memory leak detected. 11 upload listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Feed.addListener (events.js:239:17)
    at onindex (/home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/archive.js:436:18)
    at /home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/archive.js:421:7
    at /home/maf/versions/dat.haus-1466086479375/node_modules/hyperdrive/node_modules/hypercore/node_modules/subleveldown/node_modules/levelup/lib/levelup.js:230:7
```

**Comment by mafintosh** [comment]
prob fixed in 8
