### ISSUE TITLE
'Offset is out of bounds' crash bug in dat cli

### ISSUE THREAD

**Issue by pfrazee** [mafintosh/hyperdrive#73]
While running `dat . --live`, I had beaker loading the page (locally) and I got this:

Beaker's using hyperdrive 6.5.1, and dat is 11.0.2.

Error dump:

```
Share Link 6ece0d8319611a8a834e56a979f484898aaeda172ad5905de929dbceee19d34e
The Share Link is secret and only those you share it with will be able to get the files
Sharing /Users/paulfrazee/tmp/mytestdat, connected to 1/3 sources
Uploading 185.22 kB/s, 926.09 kB Totalfs.js:681
  binding.read(fd, buffer, offset, length, position, req);
          ^

Error: Offset is out of bounds
    at Error (native)
    at Object.fs.read (fs.js:681:11)
    at onread (/Users/paulfrazee/npm/lib/node_modules/dat/node_modules/random-access-file/index.js:84:8)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:675:17)
```

**Comment by mafintosh** [comment]
prob fixed in 8
