### ISSUE TITLE
Error Trying to dat share w/ Dat v1.0

### ISSUE THREAD

**Issue by joehand** [mafintosh/hyperdrive#8]
I was trying to `dat share` a large folder and got and error after a few hundred (?) files. Karissa said the issue may be hyperdrive:

```
/Users/joe/node_modules/dat/node_modules/hyperdrive/node_modules/rabin/index.js:18
  this.rabin = rabin.initialize(avgBits, min, max)
                     ^
Error: the value of instance_counter is too damn high
    at Error (native)
    at new Rabin (/Users/joe/node_modules/dat/node_modules/hyperdrive/node_modules/rabin/index.js:18:22)
    at Rabin (/Users/joe/node_modules/dat/node_modules/hyperdrive/node_modules/rabin/index.js:10:40)
    at writeStream (/Users/joe/node_modules/dat/node_modules/hyperdrive/lib/write-stream.js:22:35)
    at Archive.entry (/Users/joe/node_modules/dat/node_modules/hyperdrive/lib/pack.js:46:17)
    at DestroyableTransform._transform (/Users/joe/node_modules/dat/index.js:47:22)
    at DestroyableTransform.Transform._read (/Users/joe/node_modules/dat/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/joe/node_modules/dat/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/joe/node_modules/dat/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:333:12)
    at writeOrBuffer (/Users/joe/node_modules/dat/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:319:5)
```

**Comment by mafintosh** [comment]
this is because dat adds all files in parallel right now (which it shouldn't). /cc @karissa

**Comment by mafintosh** [comment]
i sent a pr to fix it here, https://github.com/maxogden/dat/pull/424
